global using Bazaar.Ordering.Domain.Entites;
global using Bazaar.Ordering.Domain.Exceptions;
global using Bazaar.Ordering.Domain.Interfaces;
global using Bazaar.Ordering.Infrastructure.Repositories;
global using Bazaar.Ordering.ServiceIntegration.EventHandling;
global using Bazaar.Ordering.ServiceIntegration.IntegrationEvents;
global using OrderingTests.Helpers;
global using TestingCommon.TestDoubles;
global using Xunit;
