global using Bazaar.BuildingBlocks.JsonAdapter;
global using Bazaar.ShopperInfo.Domain.Entities;
global using Bazaar.ShopperInfo.Domain.Interfaces;
global using Bazaar.ShopperInfo.Infrastructure.Database;
global using Bazaar.ShopperInfo.Infrastructure.Repositories;
global using Bazaar.ShopperInfo.Web.Messages;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.Text.Json.Serialization;