global using Bazaar.Contracting.Controllers;
global using Bazaar.Contracting.Domain.DomainLogic;
global using Bazaar.Contracting.Domain.Entities;
global using Bazaar.Contracting.DTOs;
global using Bazaar.Contracting.Repositories;
global using ContractingTests.Helpers;
global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using Xunit;
