apiVersion: v1
kind: Pod
metadata:
  annotations:
    consul.hashicorp.com/connect-inject: "false"
  creationTimestamp: "2023-07-08T08:03:14Z"
  generateName: consul-connect-injector-7fb86fc49-
  labels:
    app: consul
    chart: consul-helm
    component: connect-injector
    pod-template-hash: 7fb86fc49
    release: consul
  name: consul-connect-injector-7fb86fc49-7zp9s
  namespace: consul
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: consul-connect-injector-7fb86fc49
    uid: 65660e44-a1fe-49b8-9363-5382f523e2f8
  resourceVersion: "1838"
  uid: 29e3f2e2-0409-40a0-a9a5-be85897ac62d
spec:
  containers:
  - command:
    - /bin/sh
    - -ec
    - |
      consul-k8s-control-plane inject-connect \
        -log-level=info \
        -log-json=false \
        -default-inject=false \
        -consul-image="hashicorp/consul:1.15.3" \
        -consul-dataplane-image="hashicorp/consul-dataplane:1.1.2" \
        -consul-k8s-image="hashicorp/consul-k8s-control-plane:1.1.2" \
        -release-name="consul" \
        -release-namespace="consul" \
        -resource-prefix=consul \
        -listen=:8080 \
        -default-enable-transparent-proxy=true \
        -enable-cni=false \
        -transparent-proxy-default-overwrite-probes=true \
        -enable-consul-dns=true \
        -default-enable-metrics=false \
        -enable-gateway-metrics=true  \
        -default-enable-metrics-merging=false  \
        -default-merged-metrics-port=20100 \
        -default-prometheus-scrape-port=20200 \
        -default-prometheus-scrape-path="/metrics" \
        -acl-auth-method="consul-k8s-auth-method" \
        -allow-k8s-namespace="*" \
        -tls-cert-dir=/etc/connect-injector/certs \
        -default-envoy-proxy-concurrency=2 \
        -init-container-memory-limit=150Mi \
        -init-container-memory-request=25Mi \
        -init-container-cpu-request=50m \
        -enable-telemetry-collector=false  \
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: CONSUL_ADDRESSES
      value: consul-server.consul.svc
    - name: CONSUL_GRPC_PORT
      value: "8502"
    - name: CONSUL_HTTP_PORT
      value: "8501"
    - name: CONSUL_DATACENTER
      value: kind-bazaar
    - name: CONSUL_API_TIMEOUT
      value: 5s
    - name: CONSUL_USE_TLS
      value: "true"
    - name: CONSUL_CACERT_FILE
      value: /consul/tls/ca/tls.crt
    - name: CONSUL_LOGIN_AUTH_METHOD
      value: consul-k8s-component-auth-method
    - name: CONSUL_LOGIN_DATACENTER
      value: kind-bazaar
    - name: CONSUL_LOGIN_META
      value: component=connect-injector,pod=$(NAMESPACE)/$(POD_NAME)
    image: hashicorp/consul-k8s-control-plane:1.1.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /readyz/ready
        port: 9445
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: sidecar-injector
    ports:
    - containerPort: 8080
      name: webhook-server
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /readyz/ready
        port: 9445
        scheme: HTTP
      initialDelaySeconds: 2
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    startupProbe:
      failureThreshold: 15
      httpGet:
        path: /readyz/ready
        port: 9445
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/connect-injector/certs
      name: certs
      readOnly: true
    - mountPath: /consul/tls/ca
      name: consul-ca-cert
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-74wk8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: bazaar-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: consul-connect-injector
  serviceAccountName: consul-connect-injector
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: consul-connect-inject-webhook-cert
  - name: consul-ca-cert
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: tls.crt
      secretName: consul-ca-cert
  - name: kube-api-access-74wk8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:03:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:03:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:03:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-08T08:03:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://4c5fa8af3ea4734c0ea77dcba1940cdf9bd00d0a753432fc0c5966e3a152f362
    image: docker.io/hashicorp/consul-k8s-control-plane:1.1.2
    imageID: docker.io/hashicorp/consul-k8s-control-plane@sha256:62bed1bf8106bf344536a7efff410230e94ee069369de804338e03c4eb5a79ee
    lastState: {}
    name: sidecar-injector
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-07-08T08:03:19Z"
  hostIP: 172.18.0.2
  phase: Running
  podIP: 10.244.0.26
  podIPs:
  - ip: 10.244.0.26
  qosClass: Guaranteed
  startTime: "2023-07-08T08:03:14Z"
