apiVersion: gateway.networking.k8s.io/v1alpha2
# The Gateway is the main infrastructure resource that links API gateway components.
kind: Gateway
metadata:
 name: {{ .Values.name }}
 namespace: consul
spec:
  gatewayClassName: consul-api-gateway
  # Configures the listener that is bound to the gateway's address.
  listeners:
    # Defines the listener protocol (HTTP, HTTPS, or TCP)
  - protocol: HTTP
    port: {{ .Values.port }}
    name: http
    allowedRoutes:
      namespaces:
        from: Same
    # tls:
    #   # Defines the certificate to use for the HTTPS listener.
    #   certificateRefs:
    #   - name: consul-server-cert
    #   mode: Terminate