version: "3.4"
name: "bazaar"
services:
  webapigw:
    image: ${DOCKER_REGISTRY-}bazaar-webapigw
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-envoy

  internallb:
    image: ${DOCKER_REGISTRY-}bazaar-internallb
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-envoy

  webbff:
    image: ${DOCKER_REGISTRY-}bazaar-webbff
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=WebBff
        - service_path=ApiGateways
    depends_on:
      - payment-api
      - ordering-api
      - basket-api
      - contracting-api
      - customer-api
      - catalog-api

  catalog-api:
    image: ${DOCKER_REGISTRY-}bazaar-catalog-api
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=Catalog

  customer-api:
    image: ${DOCKER_REGISTRY-}bazaar-customer-api
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=Customer

  contracting-api:
    image: ${DOCKER_REGISTRY-}bazaar-contracting-api
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=Contracting
    
  basket-api:
    image: ${DOCKER_REGISTRY-}bazaar-basket-api
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=Basket

  ordering-api:
    image: ${DOCKER_REGISTRY-}bazaar-ordering-api
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=Ordering

  payment-api:
    image: ${DOCKER_REGISTRY-}bazaar-payment-api
    build:
      context: ../
      dockerfile: K8S/Dockerfiles/Dockerfile-dotnet
      args:
        - project_name=Payment