FROM envoyproxy/envoy:v1.26-latest

ARG config_path=ApiGateways/Envoy/web
COPY ${config_path}/envoy.yaml /etc/envoy.yaml
#RUN chmod go+r /etc/envoy/envoy.yaml
CMD /usr/local/bin/envoy -c /etc/envoy.yaml
