#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

ARG service_path=Services
ARG project_name

COPY $service_path/$project_name/$project_name.csproj $service_path/$project_name/
RUN dotnet restore "$service_path/$project_name/$project_name.csproj"

COPY ./BuildingBlocks ./BuildingBlocks
COPY ./$service_path/$project_name/ ./$service_path/$project_name/ 
WORKDIR /src/$service_path/$project_name/
RUN dotnet build "$project_name.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "$project_name.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "$project_name.dll"]
