apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app }}"
spec:
  replicas: {{ int .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: "{{ .Values.app }}"
        type: microservice
    spec:
      containers:
      - name: "{{ .Values.app }}"
        image: "{{ .Values.registry }}/{{ .Values.image }}"
        resources:
          limits:
            memory: "{{ int .Values.memory }}Mi"
            cpu: "{{ int .Values.cpu }}m"
        ports:
        - containerPort: {{ int .Values.containerPort }}
