apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-{{ .Values.name }}"
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.storage }}
  hostPath:
    path: "{{ .Values.path }}"