apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app }}"
spec:
  replicas: {{ int .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.app }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app }}"
        type: apigateway
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
    spec:
      serviceAccountName: {{ .Values.app }}-srv-http
      containers:
      - name: "{{ .Values.app }}"
        image: "{{ .Values.registry }}/bazaar-{{ .Values.image }}"
        resources:
          limits:
            memory: "{{ int .Values.memory }}Mi"
            cpu: "{{ int .Values.cpu }}m"
        ports:
        - name: admin-port
          containerPort: {{ int .Values.adminPort }}
        - name: http-port
          containerPort: {{ int .Values.httpPort }}
        env:
        - name: ENVOY_UID # Without this it can't start since envoy 1.15
          value: "0" # Alternative is to set the correct permission for envoy, lol like hell I'm gonna do that.