global:
  scrape_interval:  5s
  scrape_timeout: 3s
prometheus:
  server:
    podAnnotations:
      "consul.hashicorp.com/connect-inject": "false"
    readinessProbeInitialDelay: 0
    securityContext:
      runAsUser: 65534
      runAsNonRoot: true
      runAsGroup: 655
    persistentVolume:
      enabled: false
  alertmanager:
    enabled: false
  nodeExporter:
    podAnnotations:
      "consul.hashicorp.com/connect-inject": "false"
  pushgateway:
    podAnnotations:
      "consul.hashicorp.com/connect-inject": "false"
  kube-state-metrics:
    podAnnotations:
      "consul.hashicorp.com/connect-inject": "false"
  serviceAccounts:
    alertmanager:
      create: true
      name:
      annotations: {}
    nodeExporter:
      create: true
      name:
      annotations: {}
    pushgateway:
      create: true
      name:
      annotations: {}
    server:
      create: true
      name:
      annotations: {}
grafana:
  adminPassword: password
  rbac:
    create: false
    pspEnabled: false
  testFramework:
    enabled: false
  podLabels:
    app: grafana
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"
  service:
    port: 3000
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://monitoring-prometheus-server.default.svc.cluster.local
          access: proxy
          isDefault: true
          jsonData:
            timeInterval: 5s
          editable: true