global:
  enabled: true
  name: consul
  datacenter: dc1
  # tls:
  #   enabled: true
  acls:
    manageSystemACLs: true
    defaultPolicy: "deny"
  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"
server:
  enabled: true
  replicas: 1
ui:
  enabled: true
  service:
    type: NodePort
  metrics:
    enabled: true
    provider: "prometheus"
    baseURL: http://prometheus-server.default.svc.cluster.local
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
apiGateway:
  enabled: true
  image: "hashicorp/consul-api-gateway:0.5.1"
  managedGatewayClass:
    serviceType: NodePort
    useHostPorts: true