kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.app }}"
  namespace: default
  labels:
    app: "{{ .Values.app }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.app }}"
  ports:
  - port: {{ .Values.httpPort }}
    targetPort: {{ .Values.httpPort }}