{{ if (default .Values.expose) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app }}-ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/{{ .Values.app }}/admin(/|$)(.*)"
        backend:
          service:
            name: "{{ .Values.app }}-admin"
            port:
              number: {{ .Values.adminPort }}
      - pathType: Prefix
        path: "/{{ .Values.app }}/http(/|$)(.*)"
        backend:
          service:
            name: "{{ .Values.app }}"
            port:
              number: {{ .Values.httpPort }}
{{ end }}