apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: "eventbus-{{ .Release.Name }}-intention"
  namespace: default
# Allow traffic from nginx to frontend
spec:
  destination:
    name: {{ .Release.Name }}
  sources:
    {{- range $service := .Values.services }}
    - name: {{ $service.name }}
      action: {{ or $service.action "allow" }}
    {{- end }}
