global using Bazaar.Catalog.Domain.Entities;
global using Bazaar.Catalog.Domain.Interfaces;
global using Bazaar.Catalog.Domain.Services;
global using Bazaar.Catalog.Infrastructure.Repositories;
global using Bazaar.Catalog.ServiceIntegration.EventHandling;
global using Microsoft.EntityFrameworkCore;
global using Moq;
global using TestingCommon.TestDoubles;
global using Xunit;
