app: "template"
npMeta: "-srv-np" #e.g: template-srv-np

registry: "cornycodingcorn"
image: "template"
replicas: 2

memory: "256"
cpu: "200"

containerPort: 80
externalPort: 30200 #Has to be in [30000, 32767]