app: "template"
npMeta: "-srv-np" #e.g: template-srv-np
apiMeta: "-api" #e.g: template-api
deplMeta: "-depl"

registry: "cornycodingcorn"
image: "template"
projectName: "template" #Name of the dll file
replicas: 1

memory: "256"
cpu: "200"

containerPort: 80

#ENV
aspUrls: "http://+:80"
eventBus: "rabbitmq"
aspEnv: "Development"