apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: default-intention
spec:
  destination:
    name: "*"
  sources:
  - name: "*"
    action: {{ .Values.defaultIntention }}