version: "3.4"

services:
  webapigw:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
  # internallb:
  #   volumes:
  #     - ./ApiGateways/Envoy/web:/etc/envoy
  #   ports:
  #     - "5201:80"
  #     - "15201:8001"
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  sqldata:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=sqldata;Database=BazaarIdentity;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - WebSellerRedirectUrl=http://localhost:5004
      - WebShoppingRedirectUrl=http://localhost:5002
      - IssuerUri=http://identity-api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - ${IDENTITY_PORT}:80

  media-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ExternalHttpPort=${MEDIA_SERVER_HTTP_PORT}
      - ExternalHttpsPort=${MEDIA_SERVER_HTTPS_PORT}
      - EventBusConnection=rabbitmq
    ports:
      - ${MEDIA_SERVER_HTTP_PORT}:80
      - ${MEDIA_SERVER_HTTPS_PORT}:443

# Task scheduler
  task-scheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HangfireConnection=Server=sqldata;Database=Hangfire;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - DbServerConnection=Server=sqldata;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - FbbInventoryApi=http://fbbinventory-api
    ports:
      - "5500:80"
  
# Application services
  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarCatalog;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - MediaServerUrl=${MEDIA_SERVER_URL}
      - DisableIdentity=true
      - AllowedOrigins=http://localhost:3000
    volumes:
      - ./SeedData:/root/SeedData
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5240:80"

  fbbinventory-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      # - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarFbbInventory;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    # volumes:
      # - ./SeedData:/root/SeedData
    ports:
      - "5242:80"

  transport-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      # - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarTransport;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    # volumes:
      # - ./SeedData:/root/SeedData
    ports:
      - "5244:80"

  disposal-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      # - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarDisposal;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    # volumes:
      # - ./SeedData:/root/SeedData
    ports:
      - "5246:80"

  shopper-info-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarShopperInfo;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    volumes:
      - ./SeedData:/root/SeedData
    ports:
      - "5248:80"

  contracting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarContracting;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    volumes:
      - ./SeedData:/root/SeedData
    ports:
      - "5250:80"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarBasket;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    ports:
      - "5252:80"
    volumes:
      - ./SeedData:/root/SeedData

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/SeedData/seed_data.json
      - ConnectionString=Server=sqldata;Database=BazaarOrdering;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityApi=http://identity-api
      - DisableIdentity=true
    volumes:
      - ./SeedData:/root/SeedData
    ports:
      - "5254:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "5256:80"

# Client BFFs
  webshopping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IdentityApi=http://identity-api
      - IdentityRewriteUrl=http://localhost:5555 
      - ClientId=webshopping
      - ClientSecret=webshoppingsecret
      - CatalogApi=http://catalog-api
      - OrderingApi=http://ordering-api
      - ShopperInfoApi=http://shopper-info-api
      - BasketApi=http://basket-api
      - ContractingApi=http://contracting-api
      - DisableIdentity=true
    ports:
      - "5002:80"

  # webseller:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - REACT_APP_HTTPS_PORT=5004
  #     - IdentityApi=http://identity-api
  #     - IdentityRewriteUrl=http://localhost:5555
  #     - ClientId=webseller
  #     - ClientSecret=websellersecret
  #     - CatalogApi=http://catalog-api
  #     - OrderingApi=http://ordering-api
  #     - ContractingApi=http://contracting-api
  #   ports:
  #     - "5004:80"
