version: "3.4"
name: "bazaar"
services:
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
  customer:
    image: ${DOCKER_REGISTRY-}customer
    build:
      context: .
      dockerfile: Services/Customer/Dockerfile
  seller:
    image: ${DOCKER_REGISTRY-}seller
    build:
      context: .
      dockerfile: Services/Seller/Dockerfile
  basket:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Services/Basket/Dockerfile
  ordering:
    image: ${DOCKER_REGISTRY-}ordering
    build:
      context: .
      dockerfile: Services/Ordering/Dockerfile
