version: "3.4"
name: "bazaar"
services:
  webapigw:
    image: envoyproxy/envoy:v1.26-latest

  internallb:
    image: envoyproxy/envoy:v1.26-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
    profiles:
      - catalog
      - fbbinventory
      - ordering
      - basket
      - all
  
  identity-sql:
   image: mcr.microsoft.com/mssql/server:2022-latest
   profiles:
      - id
      - all

  catalog-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - catalog
      - all

  fbbinventory-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - fbbinventory
      - all

  transport-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - transport
      - all

  basket-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - basket
      - all

  ordering-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - ordering
      - all

  shopper-info-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - shopper-info
      - all

  contracting-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - contracting
      - all

  identity-api:
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile
    depends_on:
      - identity-sql
      - internallb
    profiles:
      - id
      - all
  
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    depends_on:
      - catalog-sql
      - internallb
      - rabbitmq
    profiles:
      - catalog
      - all

  fbbinventory-api:
    image: ${DOCKER_REGISTRY-}fbbinventory-api
    build:
      context: .
      dockerfile: Services/FbbInventory/Dockerfile
    depends_on:
      - fbbinventory-sql
      - rabbitmq
    profiles:
      - fbbinventory
      - all

  transport-api:
    image: ${DOCKER_REGISTRY-}transport-api
    build:
      context: .
      dockerfile: Services/Transport/Dockerfile
    depends_on:
      - transport-sql
      - rabbitmq
    profiles:
      - transport
      - all

  shopper-info-api:
    image: ${DOCKER_REGISTRY-}shopper-info-api
    build:
      context: .
      dockerfile: Services/ShopperInfo/Dockerfile
    depends_on:
      - internallb
      - shopper-info-sql
    profiles:
      - shopper-info
      - all

  contracting-api:
    image: ${DOCKER_REGISTRY-}contracting-api
    build:
      context: .
      dockerfile: Services/Contracting/Dockerfile
    depends_on:
      - internallb
      - contracting-sql
    profiles:
      - contracting
      - all

  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: Services/Basket/Dockerfile
    depends_on:
      - internallb
      - basket-sql
    profiles:
      - basket
      - all

  ordering-api:
    image: ${DOCKER_REGISTRY-}ordering-api
    build:
      context: .
      dockerfile: Services/Ordering/Dockerfile
    depends_on:
      - rabbitmq
      - internallb
      - ordering-sql
    profiles:
      - ordering
      - all

  payment-api:
    image: ${DOCKER_REGISTRY-}payment-api
    build:
      context: .
      dockerfile: Services/Payment/Dockerfile
    depends_on:
      - rabbitmq
    profiles:
      - ordering
      - all

  webshopping:
    image: ${DOCKER_REGISTRY-}webshopping
    build:
      context: .
      dockerfile: WebUI/WebShoppingUI/Dockerfile
    depends_on:
      - catalog-api
      - basket-api
      - ordering-api
      - shopper-info-api
    profiles:
      - webshop
      - all

  webseller:
    image: ${DOCKER_REGISTRY-}webseller
    build:
      context: .
      dockerfile: WebUI/WebSellerUI/Dockerfile
    depends_on:
      - catalog-api
      - ordering-api
      - contracting-api
      - fbbinventory-api
    profiles:
      - websell
      - all