version: "3.4"
name: "bazaar"
services:
  webapigw:
    image: envoyproxy/envoy:v1.26-latest

  internallb:
    image: envoyproxy/envoy:v1.26-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
    profiles:
      - catalog
      - fbbinventory
      - ordering
      - basket
      - disposal
      - transport
      - contracting
      - all
  
  sqldata:
   image: mcr.microsoft.com/mssql/server:2022-latest
   profiles:
      - id
      - catalog
      - fbbinventory
      - transport
      - disposal
      - basket
      - ordering
      - shopper-info
      - contracting
      - all

  identity-api:
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: Services/Identity/Dockerfile
    depends_on:
      - sqldata
      - internallb
    profiles:
      - id
      - all

  media-server:
    image: ${DOCKER_REGISTRY}media-server
    build:
      context: .
      dockerfile: Services/MediaServer/Dockerfile

  task-scheduler:
    image: ${DOCKER_REGISTRY-}task-scheduler
    build:
      context: .
      dockerfile: Services/ScheduledTasks/Dockerfile
    depends_on:
      - fbbinventory-api
      - sqldata
    profiles:
      - fbbinventory
      - all
  
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    depends_on:
      - sqldata
      - internallb
      - rabbitmq
    profiles:
      - catalog
      - all

  fbbinventory-api:
    image: ${DOCKER_REGISTRY-}fbbinventory-api
    build:
      context: .
      dockerfile: Services/FbbInventory/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    profiles:
      - fbbinventory
      - all

  transport-api:
    image: ${DOCKER_REGISTRY-}transport-api
    build:
      context: .
      dockerfile: Services/Transport/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    profiles:
      - transport
      - all

  disposal-api:
    image: ${DOCKER_REGISTRY-}disposal-api
    build:
      context: .
      dockerfile: Services/Disposal/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    profiles:
      - disposal
      - all

  shopper-info-api:
    image: ${DOCKER_REGISTRY-}shopper-info-api
    build:
      context: .
      dockerfile: Services/ShopperInfo/Dockerfile
    depends_on:
      - internallb
      - sqldata
    profiles:
      - shopper-info
      - all

  contracting-api:
    image: ${DOCKER_REGISTRY-}contracting-api
    build:
      context: .
      dockerfile: Services/Contracting/Dockerfile
    depends_on:
      - internallb
      - sqldata
      - rabbitmq
    profiles:
      - contracting
      - all

  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: Services/Basket/Dockerfile
    depends_on:
      - internallb
      - sqldata
    profiles:
      - basket
      - all

  ordering-api:
    image: ${DOCKER_REGISTRY-}ordering-api
    build:
      context: .
      dockerfile: Services/Ordering/Dockerfile
    depends_on:
      - rabbitmq
      - internallb
      - sqldata
    profiles:
      - ordering
      - all

  payment-api:
    image: ${DOCKER_REGISTRY-}payment-api
    build:
      context: .
      dockerfile: Services/Payment/Dockerfile
    depends_on:
      - rabbitmq
    profiles:
      - ordering
      - all

  webshopping:
    image: ${DOCKER_REGISTRY-}webshopping
    build:
      context: .
      dockerfile: WebUI/WebShoppingUI/Dockerfile
    depends_on:
      - catalog-api
      - basket-api
      - ordering-api
      - shopper-info-api
    profiles:
      - webshop
      - all

  webseller:
    image: ${DOCKER_REGISTRY-}webseller
    build:
      context: .
      dockerfile: WebUI/WebSellerUI/Dockerfile
    depends_on:
      - catalog-api
      - ordering-api
      - contracting-api
      - fbbinventory-api
    profiles:
      - websell
      - all