version: "3.4"

services:
  webapigw:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
  internallb:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5201:80"
      - "15201:8001"
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  identity-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5438:1433"

  catalog-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  basket-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  ordering-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5435:1433"

  shopper-info-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5436:1433"

  contracting-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5437:1433"

  webbff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ClusterId=1
      - BasketsUri=http://internallb/b/api/buyer-baskets
      - CatalogUri=http://internallb/ca/api/catalog
      - OrdersUri=http://internallb/o/api/orders
    ports:
      - "5210:80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Server=identity-sql;Database=BazaarIdentity;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - WebSellerRedirectUrl=http://localhost:5004
      - WebShoppingRedirectUrl=http://localhost:5002
      - IdentityIssuer=http://localhost:5252
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - ${IDENTITY_PORT}:80
  
  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=catalog-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
      - IdentityUrl=http://identity-api
    volumes:
      - ./Data:/root/Data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5240:80"

  shopper-info-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=shopper-info-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
    ports:
      - "5242:80"

  contracting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=contracting-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
    ports:
      - "5244:80"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=basket-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    ports:
      - "5246:80"
    volumes:
      - ./Data:/root/Data

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=ordering-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
    ports:
      - "5248:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "5250:80"

  webshopping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ClientId=webshopping
      - ClientSecret=webshoppingsecret 
    ports:
      - "5002:80"

  webseller:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - REACT_APP_HTTPS_PORT=5004
      - IdentityApi=http://identity-api
      - IdentityRewriteUrl=http://localhost:5252
      - ClientId=webseller
      - ClientSecret=websellersecret
      - CatalogUri=http://catalog-api/api/catalog
    ports:
      - "5004:80"
