version: "3.4"
name: "bazaar"
services:
  webapigw:
    image: envoyproxy/envoy:v1.26-latest

  internallb:
    image: envoyproxy/envoy:v1.26-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine
    profiles:
      - ordering

  catalog-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - catalog
      - ordering

  basket-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - basket

  ordering-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - ordering

  shopper-info-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - shopper-info

  contracting-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles:
      - contracting

  webbff:
    image: ${DOCKER_REGISTRY-}webbff
    build:
      context: .
      dockerfile: ApiGateways/WebBff/Dockerfile
    depends_on:
      - payment-api
      - ordering-api
      - basket-api
      - contracting-api
      - shopper-info-api
      - catalog-api
      - rabbitmq
    profiles:
      - webbff
  
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    depends_on:
      - catalog-sql
      - internallb
    profiles:
      - catalog
      - ordering

  shopper-info-api:
    image: ${DOCKER_REGISTRY-}shopper-info-api
    build:
      context: .
      dockerfile: Services/ShopperInfo/Dockerfile
    depends_on:
      - internallb
      - shopper-info-sql
    profiles:
      - shopper-info

  contracting-api:
    image: ${DOCKER_REGISTRY-}contracting-api
    build:
      context: .
      dockerfile: Services/Contracting/Dockerfile
    depends_on:
      - internallb
      - contracting-sql
    profiles:
      - contracting

  basket-api:
    image: ${DOCKER_REGISTRY-}basket-api
    build:
      context: .
      dockerfile: Services/Basket/Dockerfile
    depends_on:
      - internallb
      - basket-sql
    profiles:
      - basket

  ordering-api:
    image: ${DOCKER_REGISTRY-}ordering-api
    build:
      context: .
      dockerfile: Services/Ordering/Dockerfile
    depends_on:
      - rabbitmq
      - internallb
      - ordering-sql
    profiles:
      - ordering

  payment-api:
    image: ${DOCKER_REGISTRY-}payment-api
    build:
      context: .
      dockerfile: Services/Payment/Dockerfile
    depends_on:
      - rabbitmq
    profiles:
      - ordering
