version: "3.4"

services:
  webapigw:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
  internallb:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5201:80"
      - "15201:8001"
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  catalog-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  basket-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  ordering-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5435:1433"

  shopper-info-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5436:1433"

  contracting-sql:
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5437:1433"

  webbff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ClusterId=1
      - CoordinatorUri=http://internallb/ca/api/coordinator
      - CatalogServiceUri=http://internallb/ca/api
      - OrderServiceUri=http://internallb/o/api
    ports:
      - "5210:80"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - CatalogServiceUri=http://internallb/ca/api
      - CustomerServiceUri=http://internallb/cs/api
      - PartnerServiceUri=http://internallb/ct/api
      - OrderServiceUri=http://internallb/o/api
      - BasketServiceUri=http://internallb/ba/api
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=catalog-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5240:80"

  shopper-info-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=shopper-info-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
    ports:
      - "5242:80"

  contracting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=contracting-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
    ports:
      - "5244:80"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=basket-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    ports:
      - "5246:80"
    volumes:
      - ./Data:/root/Data

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - SeedDataFilePath=/root/Data/data.json
      - ConnectionString=Server=ordering-sql;Database=Bazaar;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=true
    volumes:
      - ./Data:/root/Data
    ports:
      - "5248:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "5250:80"
