version: "3.4"

services:
  webapigw:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
  internallb:
    volumes:
      - ./ApiGateways/Envoy/web:/etc/envoy
    ports:
      - "5201:80"
      - "15201:8001"
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - CatalogServiceUri=http://internallb:80/ca/api/catalog
      - CustomerServiceUri=http://internallb:80/cs/api/customer
      - PartnerServiceUri=http://internallb:80/ct/api/partner
      - DataStorePath=/root/Data/data.json
    volumes:
      - ./Data:/root/Data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5240:80"
  customer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - DataStorePath=/root/Data/data.json
    volumes:
      - ./Data:/root/Data
    ports:
      - "5242:80"
  contracting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - DataStorePath=/root/Data/data.json
    volumes:
      - ./Data:/root/Data
    ports:
      - "5244:80"
  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "5246:80"
  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
      - ClusterId=1
      - CoordinatorUri=http://internallb:80/ca/api/coordinator
      - CatalogServiceUri=http://internallb:80/ca/api/catalog
      - DataStorePath=/root/Data/data.json
    volumes:
      - ./Data:/root/Data
    ports:
      - "5248:80"
  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusConnection=rabbitmq
    ports:
      - "5250:80"
