global using Ardalis.Result;
global using Bazaar.Basket.Application.DTOs;
global using Bazaar.Basket.Application.IntegrationEvents;
global using Bazaar.Basket.Application.Services;
global using Bazaar.Basket.Domain.Entites;
global using Bazaar.Basket.Domain.Interfaces;
global using Bazaar.Basket.Infrastructure.Repositories;
global using TestingCommon.TestDoubles;
global using Xunit;
